# permissions for end users to view pings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ping-viewer-role
rules:
- apiGroups:
  - demo.mikevasylchenko
  resources:
  - pings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.mikevasylchenko
  resources:
  - pings/status
  verbs:
  - get
